import {
  Award,
  BedDouble,
  BookOpen,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Contact,
  FileText,
  GraduationCap,
  HeartPulse,
  History,
  Library,
  Megaphone,
  MessageSquareWarning,
  NotebookText,
  Package,
  ShieldAlert,
  ShoppingCart,
  Truck,
  Users,
  Video,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/** One card per module on the Dashboard's "Module summaries" section — each backed by that
 * module's own `GET {resource}/summary/` endpoint (the generic `SummaryStatsMixin` action every
 * domain ViewSet already exposes). `permission` reuses the exact same string(s) `navConfig.ts`
 * gates that module's sidebar entry with, so a card only ever appears for someone who could also
 * reach the module itself — deliberately not re-deriving a parallel gating rule. `breakdownKey`
 * names the `summary_stats` entry that holds a `{groupby: "..."}` result (a `Record<string,
 * number>`), rendered as a small pie chart; modules without one just show their headline
 * number(s). */
export interface ModuleSummaryConfig {
  key: string;
  to: string;
  label: string;
  icon: LucideIcon;
  permission?: string | string[];
  resource: string;
  primaryKey: string;
  primaryLabel: string;
  secondaryKey?: string;
  secondaryLabel?: string;
  breakdownKey?: string;
}

export const MODULE_SUMMARY_CONFIG: ModuleSummaryConfig[] = [
  {
    key: "students",
    to: "/students",
    label: "Students",
    icon: GraduationCap,
    permission: "students.view",
    resource: "students",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "active",
    secondaryLabel: "Active",
    breakdownKey: "by_status",
  },
  {
    key: "staff",
    to: "/staff",
    label: "Staff",
    icon: Users,
    permission: "staff.view",
    resource: "staff",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "active",
    secondaryLabel: "Active",
    breakdownKey: "by_status",
  },
  {
    key: "academics",
    to: "/academics/classes",
    label: "Academics",
    icon: BookOpen,
    permission: "academics.view",
    resource: "academics/classes",
    primaryKey: "total",
    primaryLabel: "Classes",
  },
  {
    key: "timetable",
    to: "/timetable/periods",
    label: "Timetable",
    icon: CalendarClock,
    permission: "timetable.view",
    resource: "timetable/periods",
    primaryKey: "total",
    primaryLabel: "Periods",
    secondaryKey: "breaks",
    secondaryLabel: "Breaks",
  },
  {
    key: "examinations",
    to: "/examinations/results",
    label: "Examinations",
    icon: Award,
    permission: "results.view",
    resource: "results",
    primaryKey: "total",
    primaryLabel: "Results",
    breakdownKey: "by_status",
  },
  {
    key: "finance",
    to: "/finance/invoices",
    label: "Finance",
    icon: Wallet,
    permission: "fees.view",
    resource: "finance/invoices",
    primaryKey: "total",
    primaryLabel: "Invoices",
    breakdownKey: "by_status",
  },
  {
    key: "library",
    to: "/library/books",
    label: "Library",
    icon: Library,
    permission: "library.view",
    resource: "library/copies",
    primaryKey: "total",
    primaryLabel: "Copies",
    secondaryKey: "available",
    secondaryLabel: "Available",
    breakdownKey: "by_status",
  },
  {
    key: "transport",
    to: "/transport/vehicles",
    label: "Transport",
    icon: Truck,
    permission: "transport.view",
    resource: "transport/vehicles",
    primaryKey: "total",
    primaryLabel: "Vehicles",
    secondaryKey: "active",
    secondaryLabel: "Active",
    breakdownKey: "by_status",
  },
  {
    key: "hostel",
    to: "/hostel/allocations",
    label: "Hostel",
    icon: BedDouble,
    permission: "hostel.view",
    resource: "hostel/allocations",
    primaryKey: "total",
    primaryLabel: "Allocations",
    secondaryKey: "active",
    secondaryLabel: "Active",
    breakdownKey: "by_status",
  },
  {
    key: "medical",
    to: "/medical/visits",
    label: "Medical",
    icon: HeartPulse,
    permission: "medical.view",
    resource: "medical/visits",
    primaryKey: "total",
    primaryLabel: "Visits",
    secondaryKey: "incident",
    secondaryLabel: "Incidents",
  },
  {
    key: "parents",
    to: "/parents",
    label: "Parents",
    icon: Contact,
    permission: "parents.view",
    resource: "parents",
    primaryKey: "total",
    primaryLabel: "Guardians",
  },
  {
    key: "discipline",
    to: "/discipline",
    label: "Discipline",
    icon: ShieldAlert,
    permission: "discipline.view",
    resource: "discipline/incidents",
    primaryKey: "total",
    primaryLabel: "Incidents",
    secondaryKey: "reported",
    secondaryLabel: "Reported",
    breakdownKey: "by_severity",
  },
  {
    key: "communications",
    to: "/communications",
    label: "Communications",
    icon: Megaphone,
    permission: "communications.view",
    resource: "communications/announcements",
    primaryKey: "total",
    primaryLabel: "Announcements",
    secondaryKey: "active",
    secondaryLabel: "Active",
    breakdownKey: "by_target_type",
  },
  {
    key: "events",
    to: "/events",
    label: "Events",
    icon: CalendarDays,
    permission: "events.view",
    resource: "events",
    primaryKey: "total",
    primaryLabel: "Events",
    secondaryKey: "upcoming",
    secondaryLabel: "Upcoming",
    breakdownKey: "by_status",
  },
  {
    key: "complaints",
    to: "/complaints",
    label: "Complaints",
    icon: MessageSquareWarning,
    resource: "complaints",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "submitted",
    secondaryLabel: "Submitted",
    breakdownKey: "by_status",
  },
  {
    key: "assignments",
    to: "/assignments",
    label: "Assignments",
    icon: ClipboardList,
    permission: "assignments.view",
    resource: "assignments",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "active",
    secondaryLabel: "Active",
  },
  {
    key: "education",
    to: "/education/lessons",
    label: "Lessons",
    icon: NotebookText,
    permission: "education.view",
    resource: "education/lessons",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "active",
    secondaryLabel: "Active",
  },
  {
    key: "live_sessions",
    to: "/live-sessions",
    label: "Live Sessions",
    icon: Video,
    permission: "live_sessions.view",
    resource: "live-sessions",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "live",
    secondaryLabel: "Live now",
    breakdownKey: "by_status",
  },
  {
    key: "documents",
    to: "/documents/files",
    label: "Documents",
    icon: FileText,
    permission: "documents.view",
    resource: "documents",
    primaryKey: "total",
    primaryLabel: "Total",
    secondaryKey: "confidential",
    secondaryLabel: "Confidential",
  },
  {
    key: "inventory",
    to: "/inventory/items",
    label: "Inventory",
    icon: Package,
    permission: "inventory.view",
    resource: "inventory/items",
    primaryKey: "total",
    primaryLabel: "Items",
    secondaryKey: "active",
    secondaryLabel: "Active",
  },
  {
    key: "procurement",
    to: "/procurement/requests",
    label: "Procurement",
    icon: ShoppingCart,
    permission: "procurement.view",
    resource: "procurement/requests",
    primaryKey: "total",
    primaryLabel: "Requests",
    breakdownKey: "by_status",
  },
  {
    key: "audit",
    to: "/audit",
    label: "Audit log",
    icon: History,
    permission: "audit.view",
    resource: "audit",
    primaryKey: "total",
    primaryLabel: "Entries",
    breakdownKey: "by_severity",
  },
];
