# Generated by Django 5.2.17 on 2026-08-31 12:09

import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', validators=[apps.common.validators.validate_upload_file])),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(upload_to='submissions/', validators=[apps.common.validators.validate_upload_file])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded')], default='submitted', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.CharField(blank=True, max_length=1000)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student')),
            ],
            options={
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__isnull', True), _connector='OR'), name='submission_score_non_negative')],
            },
        ),
    ]
