# Generated by Django 5.2.17 on 2026-09-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_ca_weight_percent_and_more'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.term'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
