# Generated by Django 5.2.17 on 2026-08-31 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'hostel_beds',
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('gender_restriction', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wardened_hostels', to='staff.staff')),
            ],
            options={
                'db_table': 'hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out')], default='active', max_length=20)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.bed')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student')),
            ],
            options={
                'db_table': 'hostel_allocations',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'hostel_rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room'),
        ),
        migrations.AddConstraint(
            model_name='hostel',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_hostel_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bed',), name='unique_active_allocation_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_allocation_per_student'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hostel', 'room_number'), name='unique_room_number_per_hostel'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_bed_number_per_room'),
        ),
    ]
