# Generated by Django 5.2.17 on 2026-09-03 22:49

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_photos/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
