# Generated by Django 5.2.17 on 2026-09-25 03:28

from django.db import migrations, models


def flag_accounts_still_on_the_default_password(apps, schema_editor):
    """Accounts that already exist and never changed the guessable school default must be forced to
    change it too - not only accounts provisioned from now on."""
    from django.contrib.auth.hashers import check_password

    from apps.tenants.services import generate_default_password

    User = apps.get_model("users", "User")
    for user in User.objects.exclude(school=None).select_related("school").iterator():
        default = generate_default_password(user.school)
        if user.password and check_password(default, user.password):
            User.objects.filter(pk=user.pk).update(must_change_password=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_lockout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flag_accounts_still_on_the_default_password, migrations.RunPython.noop),
    ]
