# Generated by Django 5.2.17 on 2026-08-31 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('allergies', models.CharField(blank=True, max_length=500)),
                ('chronic_conditions', models.CharField(blank=True, max_length=500)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='students.student')),
            ],
            options={
                'db_table': 'medical_profiles',
            },
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('routine', 'Routine'), ('incident', 'Incident'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('visited_at', models.DateTimeField()),
                ('symptoms', models.CharField(blank=True, max_length=500)),
                ('treatment', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('parent_notified', models.BooleanField(default=False)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_visits_attended', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='students.student')),
            ],
            options={
                'db_table': 'medical_visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
