# Generated by Django 5.2.17 on 2026-10-01 05:13

from django.db import migrations, models


def recognise_previously_customized_roles(apps, schema_editor):
    """Until now, editing a default role's permissions flipped it to `is_system=False` — but the next
    resync matched it by slug, re-pinned it and overwrote the edits. A default-slug role that is no
    longer flagged as system is therefore one a school customized: mark it as such and as already
    knowing every permission that exists today, so nothing is added or taken away from it."""
    from apps.authorization.catalog import DEFAULT_ROLE_PERMISSION_PREFIXES, PERMISSION_CATALOG

    Role = apps.get_model("authorization", "Role")
    codes = sorted(code for code, _name, _module in PERMISSION_CATALOG)
    Role.objects.filter(slug__in=list(DEFAULT_ROLE_PERMISSION_PREFIXES), is_system=False).update(
        is_system=True, customized=True, known_permission_codes=codes
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='known_permission_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(recognise_previously_customized_roles, migrations.RunPython.noop),
    ]
