# Generated by Django 5.2.17 on 2026-08-31 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='students.student'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='students',
            field=models.ManyToManyField(related_name='guardians', through='parents.StudentGuardian', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian_pair'),
        ),
    ]
