# Generated by Django 5.2.17 on 2026-09-04 08:05

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='guardian_photos/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
