# Generated by Django 5.2.17 on 2026-09-30 17:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0003_student_middle_name'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('card_number', models.CharField(max_length=32)),
                ('verify_token', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('qr_svg', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('replaced', 'Replaced')], default='active', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student')),
            ],
            options={
                'db_table': 'id_cards',
                'ordering': ['-issued_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('holder_type', 'student'), ('staff__isnull', True), ('student__isnull', False)), models.Q(('holder_type', 'staff'), ('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='idcard_exactly_one_holder'), models.UniqueConstraint(fields=('school', 'card_number'), name='unique_idcard_number_per_school'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='one_active_idcard_per_student'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('staff',), name='one_active_idcard_per_staff')],
            },
        ),
    ]
