# Generated by Django 5.2.17 on 2026-08-31 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academic_year_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_department_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school_class', 'academic_year', 'name'), name='unique_section_per_class_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_term_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_end_after_start'),
        ),
    ]
