# Generated by Django 5.2.17 on 2026-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ca_weight_percent',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_weight_percent',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
