# Generated by Django 5.2.17 on 2026-09-17 09:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_term_sequence(apps, schema_editor):
    """Existing Term rows all default to sequence=1 on AddField above — assign real,
    per-academic-year-unique sequence numbers (ordered by start_date) before the uniqueness
    constraint below is added, so schools with real multi-term data don't hit an
    IntegrityError mid-migration."""
    Term = apps.get_model("academics", "Term")
    AcademicYear = apps.get_model("academics", "AcademicYear")
    for academic_year in AcademicYear.objects.all():
        terms = Term.objects.filter(academic_year=academic_year).order_by("start_date", "id")
        for index, term in enumerate(terms, start=1):
            if term.sequence != index:
                term.sequence = index
                term.save(update_fields=["sequence"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_ca_weight_percent_and_more'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['sequence', 'start_date']},
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_graduation_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_public_exam_transition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='term',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_term_sequence, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'sequence'), name='unique_term_sequence_per_year'),
        ),
    ]
