# Generated by Django 5.2.17 on 2026-09-17 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_term_options_schoolclass_is_graduation_level_and_more'),
        ('staff', '0001_initial'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ca_weight_percent', models.PositiveIntegerField(default=40)),
                ('exam_weight_percent', models.PositiveIntegerField(default=60)),
                ('pass_mark', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.academicyear')),
                ('assistant_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_subject_offerings', to='staff.staff')),
                ('main_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_subject_offerings', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.term')),
            ],
            options={
                'db_table': 'subject_offerings',
                'ordering': ['-academic_year__start_date', 'term__sequence', 'school_class__order', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'academic_year', 'term', 'school_class'), name='unique_subject_offering_per_term_class'), models.CheckConstraint(condition=models.Q(('ca_weight_percent__gte', 0), ('exam_weight_percent__gte', 0)), name='subject_offering_weights_non_negative')],
            },
        ),
    ]
