# Generated by Django 5.2.17 on 2026-09-17 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subjectoffering'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='students.student')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'student_subject_enrollments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('subject_offering', 'student'), name='unique_student_subject_enrollment')],
            },
        ),
    ]
