# Generated by Django 5.2.17 on 2026-09-17 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentsubjectenrollment'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='ca_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='ca_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='ca_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.assessment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='students.student')),
            ],
            options={
                'db_table': 'assessment_scores',
                'ordering': ['student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='unique_assessment_score_per_student'), models.CheckConstraint(condition=models.Q(('raw_score__gte', 0), ('raw_score__isnull', True), _connector='OR'), name='assessment_score_non_negative')],
            },
        ),
    ]
