# Generated by Django 5.2.17 on 2026-09-17 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subjectoffering_ca_closed_at_and_more'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='exam_max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exam_results', to='students.student')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'subject_results',
                'ordering': ['student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('subject_offering', 'student'), name='unique_subject_result_per_student'), models.CheckConstraint(condition=models.Q(('exam_score__gte', 0), ('exam_score__isnull', True), _connector='OR'), name='subject_result_exam_score_non_negative')],
            },
        ),
    ]
