# Generated by Django 5.2.17 on 2026-09-17 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subjectoffering_exam_max_score_subjectresult'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('threshold_percent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Failed — Repeat'), ('public_exam_required', 'Public Examination Required')], max_length=25)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('public_exam', 'Public Examination'), ('manual', 'Manual')], max_length=15)),
                ('external_exam_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_applicable', max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.academicyear')),
                ('new_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.schoolclass')),
                ('previous_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('previous_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.schoolclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student')),
            ],
            options={
                'db_table': 'promotion_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
