# Generated by Django 5.2.17 on 2026-09-26 23:57, hand-edited to carry existing single-department
# assignments over into the new many-to-many before dropping the old column — otherwise every
# subject's department on a live database (this one included) would silently be lost.

from django.db import migrations, models


def copy_department_into_m2m(apps, schema_editor):
    Subject = apps.get_model("academics", "Subject")
    for subject in Subject.objects.exclude(department__isnull=True):
        subject.departments.add(subject.department_id)


def noop_reverse(apps, schema_editor):
    """One-way: a subject with more than one department can't be un-split into a single FK
    value, so there's nothing sensible to restore on a reverse migration."""


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subjectmaterial_subjectmessage_subjectprivatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.department'),
        ),
        migrations.RunPython(copy_department_into_m2m, noop_reverse),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
