# Generated by Django 5.2.17 on 2026-09-27 00:05

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_subject_department_subject_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='subject_offering_covers/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
