# Generated by Django 5.2.17 on 2026-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_subjectoffering_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
