# Generated by Django 5.2.17 on 2026-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_academicyear_archived_at_academicyear_is_archived'),
        ('students', '0003_student_middle_name'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='discretionary_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='discretionary_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('discretionary_weight__lte', models.F('weight'))), name='assessment_discretionary_within_weight'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.CheckConstraint(condition=models.Q(('discretionary_mark__gte', 0), ('discretionary_mark__isnull', True), _connector='OR'), name='assessment_discretionary_mark_non_negative'),
        ),
    ]
