# Generated by Django 5.2.17 on 2026-09-08 14:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'salary_structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('payment_number', models.CharField(max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.staff')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='salary.salarystructure')),
            ],
            options={
                'db_table': 'salary_payments',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('basic', 'Basic Pay'), ('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salary.salarystructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'salary_structure_items',
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='salary.salarystructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignment', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_salary_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_salary_structure_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(fields=('staff', 'period_year', 'period_month'), name='unique_salary_payment_per_staff_per_month'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(fields=('school', 'payment_number'), name='unique_salary_payment_number_per_school'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_structure_item_amount_positive'),
        ),
    ]
