# Generated by Django 5.2.17 on 2026-09-08 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='target_type',
            field=models.CharField(choices=[('class_section', 'Class / Section'), ('specific_students', 'Specific Students')], default='class_section', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveSessionRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='live_sessions.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.student')),
            ],
            options={
                'db_table': 'live_session_recipients',
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_live_session_recipient')],
            },
        ),
    ]
