# Generated by Django 5.2.17 on 2026-09-08 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('students', '0002_remove_student_photo_url_student_photo'),
        ('tenants', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='target_type',
            field=models.CharField(choices=[('class_section', 'Class / Section'), ('specific_students', 'Specific Students')], default='class_section', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.student')),
            ],
            options={
                'db_table': 'lesson_enrollments',
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_lesson_enrollment')],
            },
        ),
    ]
