# Generated by Django 5.2.17 on 2026-08-30 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('school_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('combined', 'Combined'), ('tertiary', 'Tertiary'), ('other', 'Other')], default='other', max_length=20)),
                ('ownership_type', models.CharField(choices=[('public', 'Public/Government'), ('private', 'Private'), ('religious', 'Religious/Mission'), ('ngo', 'NGO/Non-profit'), ('other', 'Other')], default='other', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('suspended_reason', models.CharField(blank=True, max_length=500)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
    ]
