# Generated by Django 5.2.17 on 2026-09-04 07:47

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='school_logos/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
