# Generated by Django 5.2.17 on 2026-09-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='promotion_threshold_percent',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_threshold_percent__gte', 0), ('promotion_threshold_percent__lte', 100)), name='promotion_threshold_percent_range'),
        ),
    ]
