# Generated by Django 5.2.17 on 2026-08-31 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('bullying', 'Bullying'), ('vandalism', 'Vandalism'), ('tardiness', 'Tardiness'), ('academic_dishonesty', 'Academic Dishonesty'), ('fighting', 'Fighting'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('action_taken', models.CharField(choices=[('none', 'None'), ('warning', 'Warning'), ('detention', 'Detention'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('parent_notified', models.BooleanField(default=False)),
                ('follow_up_notes', models.CharField(blank=True, max_length=1000)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='students.student')),
            ],
            options={
                'db_table': 'discipline_incidents',
                'ordering': ['-incident_date'],
            },
        ),
    ]
