# Generated by Django 5.2.17 on 2026-09-02 13:56

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
