# Generated by Django 5.2.17 on 2026-10-01 00:05

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='announcement_images/', validators=[apps.common.validators.validate_image_file]),
        ),
    ]
