# Generated by Django 5.2.17 on 2026-10-01 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    """Until now `published_by` was set to the creator when an announcement was created (despite its
    name) — carry that over so existing announcements keep an owner."""
    Announcement = apps.get_model("communications", "Announcement")
    Announcement.objects.filter(created_by__isnull=True, published_by__isnull=False).update(
        created_by=models.F("published_by")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_announcement_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_created_by, migrations.RunPython.noop),
    ]
