# Generated by Django 5.2.17 on 2026-09-29 02:34

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_academicyear_archived_at_academicyear_is_archived'),
        ('authorization', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0003_student_middle_name'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=500)),
                ('interview_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applying_for_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.schoolclass')),
                ('applying_for_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorization.role')),
                ('created_staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='staff.staff')),
                ('created_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='admission_documents/', validators=[apps.common.validators.validate_upload_file])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'admission_application_documents',
                'ordering': ['created_at'],
            },
        ),
    ]
