# Generated by Django 5.2.17 on 2026-10-01 00:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ApplicationFormConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'admission_form_configs',
                'constraints': [models.UniqueConstraint(fields=('school', 'kind'), name='unique_application_form_config_per_kind')],
            },
        ),
    ]
