# Generated by Django 5.2.17 on 2026-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_application_custom_answers_applicationformconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='question_key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
