# Generated by Django 5.2.17 on 2026-09-30 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0003_guardian_photo'),
        ('staff', '0001_initial'),
        ('students', '0003_student_middle_name'),
        ('tenants', '0003_school_promotion_threshold_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('include_all_staff', models.BooleanField(default=False)),
                ('include_all_parents', models.BooleanField(default=False)),
                ('include_all_students', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('daily_room_name', models.CharField(blank=True, max_length=255)),
                ('daily_room_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('staff', 'Staff'), ('parent', 'Parent'), ('student', 'Student')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('no_email', 'No email address')], default='pending', max_length=10)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parents.guardian')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='meetings.meeting')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_invitees',
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['meeting', 'email_status'], name='meeting_inv_meeting_7f7998_idx')],
            },
        ),
    ]
